%% load

if ~exist('A','var')
    
    fprintf('\nloading data...\n\n')
    
    A = load('soen_SWI.mat');
    
    A_growth = A.A_growth;
    A_rand = A.A_rand;
    
    
    fprintf('\ndone loading data.\n\n')
    
end

%% plot adjacency matrices

figure;
imagesc(A_growth);
colormap(gray);
colorbar
axis image
title('Adjacency matrix generated with growth algorithm','FontSize',16)

figure;
imagesc(A_rand);
colormap(gray);
colorbar
axis image
title('Adjacency matrix of random graph','FontSize',16)

%% convert to digraphs

dG_growth = digraph(A_growth);
dG_rand = digraph(A_rand);

%% calculate average path length

fprintf('\n\nCalculating average path lengths...\n\n')

shortestPathDistances_growth = distances(dG_growth);
averagePathLength_growth = mean2(shortestPathDistances_growth);

shortestPathDistances_rand = distances(dG_rand);
averagePathLength_rand = mean2(shortestPathDistances_rand);

fprintf('\n\nThe average path length of the network generated by the growth algorithm is %g\n\n',averagePathLength_growth)
fprintf('\n\nThe average path length of the random network is %g\n\n',averagePathLength_rand)

%% calculate clustering coefficients

fprintf('\n\nCalculating clustering coefficients...\n\n')

cc_growth = f_clusteringCoefficient(A_growth);
cc_rand = f_clusteringCoefficient(A_rand);

fprintf('\n\nThe average clustering coefficient of the network generated by the growth algorithm is %g\n\n',cc_growth)
fprintf('\n\nThe average clustering coefficient of the random network is %g\n\n',cc_rand)

%% calculate small-world index

fprintf('\n\nA graph is considered small-world if:\n1. Its average local clustering coefficient is significantly higher than a random graph with the same number of edges constructed on the same vertex set\n2. The graph has approximately the same mean-shortest path length as the corresponding random graph.\n\n\n')

swi = (cc_growth/cc_rand)*(averagePathLength_rand/averagePathLength_growth);
fprintf('\nDefine small-world index (SWI) as CC/CC_rand * APL_rand/APL \n')
fprintf('\nSWI = %g \n\n\n',swi)



    # function [cc] = f_clusteringCoefficient(A)

    # dG = digraph(A);
    
    # numTriangles_local = diag((A+A')^3);
    
    # inDeg = indegree(dG);
    # outDeg = outdegree(dG);
    # degTot = inDeg+outDeg;
    # degBiLat = diag(A^2);
    
    # clustCoeffVec = numTriangles_local./(2*(degTot.*(degTot-1)-2*degBiLat)); 
    
    # cc = mean(clustCoeffVec);
